### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by Xiong5Heng** [kwpoon/SDF-Pack#1]
Hi, 

Could you kindly let me know when the code will be open-sourced as stated in the paper? I am excited about the prospect of gaining a more in-depth understanding of your research by studying the code and potentially making my own contributions in the relevant field.

**Comment by kwpoon** [comment]
Hi,

Thank you for your interest. We are now cleaning up the codes which are also for commercial usage, and will release them when ready. 

Best,
JH
